name: iOS
minimum_xcode_version: 14.0

options:
  bundleIdPrefix: com.celiny
  deploymentTarget:
    iOS: 16.0
  createIntermediateGroups: true

settings:
  SWIFT_VERSION: 5.9
  PRODUCT_BUNDLE_IDENTIFIER: com.celiny.app
  MARKETING_VERSION: "1.0"
  CURRENT_PROJECT_VERSION: "1"

targets:
  Celiny:
    type: application
    platform: iOS
    sources:
      - path: Celiny
        excludes:
          - "*.md"
    settings:
      INFOPLIST_FILE: Celiny/Resources/Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.celiny.app
      TARGETED_DEVICE_FAMILY: "1"
      CODE_SIGN_IDENTITY: ""
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ""
    dependencies: []
    scheme:
      testTargets: []
      gatherCoverageData: false
    info:
      path: Celiny/Resources/Info.plist
      properties:
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
