name: Celiny
options:
  bundleIdPrefix: com.celiny
  deploymentTarget:
    iOS: 16.0
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

settings:
  base:
    PRODUCT_NAME: Celiny
    SWIFT_VERSION: 5.9
    MARKETING_VERSION: "1.0"
    CURRENT_PROJECT_VERSION: "1"
    IPHONEOS_DEPLOYMENT_TARGET: 16.0

targets:
  Celiny:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Celiny
    info:
      path: Celiny/Resources/Info.plist
      properties:
        CFBundleDisplayName: Celiny
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.celiny.app
        INFOPLIST_FILE: Celiny/Resources/Info.plist
        CODE_ENTITLEMENTS: Celiny/Resources/Celiny.entitlements
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SWIFT_VERSION: 5.9
        CODE_SIGN_IDENTITY: ""
        CODE_SIGN_STYLE: Manual
        DEVELOPMENT_TEAM: ""
    scheme:
      testTargets: []
      gatherCoverageData: false

schemes:
  Celiny:
    build:
      targets:
        Celiny: all
    run:
      config: Debug
    archive:
      config: Release
